--insert books
insert into book(title, author, year) values('Мертвые души', 'Николай Гоголь', 1842);
insert into book(title, author, year) values('Айвенго', 'Вальтер Скотт', 1820);
insert into book(title, author, year) values('Отверженные', 'Виктор Гюго', 1862);
insert into book(title, author, year) values('Вишнёвый сад', 'Антон Чехов', 1904);
insert into book(title, author, year) values('Фауст', 'Иоганн Вольфганг Гёте', 1808);
insert into book(title, author, year) values('Сто лет одиночества', 'Габриэль Гарсиа Маркес', 1967);
insert into book(title, author, year) values('Палата номер 6', 'Антон Чехов', 1892);
insert into book(title, author, year) values('Повесть о настоящем человеке', 'Борис Пастернак', 1956);
insert into book(title, author, year) values('Три товарища', 'Эрих Мария Ремарк', 1936);
insert into book(title, author, year) values('Приключения Тома Сойера', 'Марк Твен', 1876);
insert into book(title, author, year) values('Мартин Иден', 'Джек Лондон', 1909);
insert into book(title, author, year) values('Записки из подполья', 'Фёдор Достоевский', 1864);
insert into book(title, author, year) values('Капитанская дочка', 'Александр Пушкин', 1836);
insert into book(title, author, year) values('Лолита', 'Владимир Набоков', 1955);
insert into book(title, author, year) values('Дети капитана Гранта', 'Жюль Верн', 1868);
insert into book(title, author, year) values('Мастер Золотой Ключик', 'Лев Толстой', 1902);
insert into book(title, author, year) values('Заводной апельсин', 'Энтони Бёрджесс', 1962);
insert into book(title, author, year) values('Великий и ужасный', 'Фрэнсис Брет Гарт', 1899);
insert into book(title, author, year) values('Белый пик', 'Герман Мелвилл', 1851);
insert into book(title, author, year) values('Джейн Эйр', 'Шарлотта Бронте', 1847);
--insert people
insert into person(full_name, date_of_birth, phone_number, email) values('Смирнова Екатерина Петровна', '10/08/1995', '9641750832', 'katesm@gmail.com');
insert into person(full_name, date_of_birth, phone_number, email) values('Белова Мария Игоревна', '22/05/1998', '9995552991', 'marybel@yandex.ru');
insert into person(full_name, date_of_birth, phone_number, email) values('Кузнецов Даниил Владимирович', '15/12/1992', '9127241557', 'danilka@rambler.ru');
insert into person(full_name, date_of_birth, phone_number, email) values('Федоров Никита Андреевич', '02/03/1997', '9870123456', 'nikfed@inbox.ru');
insert into person(full_name, date_of_birth, phone_number, email) values('Сидоров Алексей Дмитриевич', '28/09/1990', '9097776655', 'sidoralexei@yandex.ru');
insert into person(full_name, date_of_birth, phone_number, email) values('Лебедев Михаил Александрович', '19/06/1987', '9054321766', 'mihleb@mail.ru');
insert into person(full_name, date_of_birth, phone_number, email) values('Новикова Дарья Сергеевна', '11/01/1999', '9856320147', 'novikdasha@gmail.com');
insert into person(full_name, date_of_birth, phone_number, email) values('Иванов Сергей Петрович', '07/11/1985', '9161234567', 'sergivan@ya.ru');
insert into person(full_name, date_of_birth, phone_number, email) values('Ковалев Артем Александрович', '04/02/1996', '9034567890', 'artkoval@mail.ru');
insert into person(full_name, date_of_birth, phone_number, email) values('Соколова Анастасия Игоревна', '30/07/1994', '9771234506', 'sokolana@rambler.ru');
insert into person(full_name, date_of_birth, phone_number, email) values('Куликова Алина Александровна', '12/09/2001', '9268420137', 'alikulik@gmail.com');
insert into person(full_name, date_of_birth, phone_number, email) values('Васильева Елена Михайловна', '08/04/1989', '9109876543', 'vaselena@yandex.ru');
insert into person(full_name, date_of_birth, phone_number, email) values('Григорьева Анна Александровна', '17/12/1997', '9034561234', 'annagrigor@mail.ru');